---
# https://megalinter.io/latest/configuration/
DISABLE_ERRORS_LINTERS:
  - REPOSITORY_CHECKOV
  - TERRAFORM_CHECKOV
  - TERRAFORM_TERRASCAN
  - SPELL_CSPELL
  - SPELL_LYCHEE
  - MARKDOWN_MARKDOWN_LINK_CHECK
